# Generated by Django 5.1.5 on 2025-02-04 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Noticia')),
                ('content', models.TextField(verbose_name='Contenido de la Noticia')),
                ('published_date', models.DateField(verbose_name='Fecha de Publicación')),
                ('is_featured', models.BooleanField(default=False, verbose_name='¿Destacada?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
