# Generated by Django 5.1.5 on 2025-02-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('mission', models.TextField(blank=True, null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='Visión')),
                ('history', models.TextField(blank=True, null=True, verbose_name='Historia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
        ),
    ]
